export const campgrounds = [
  {
    id: '1',
    name: 'Tahoe Valley Campground',
    slug: 'tahoe-valley',
    description: 'Large family-friendly RV resort run by Encore/Thousand Trails near South Lake Tahoe. Two pools, dog park, basketball, pickleball, and more. Ground fires prohibited May–Nov.',
    location: 'South Lake Tahoe, CA',
    lat: 38.9183,
    lng: -120.0324,
    price_per_night: 75,
    price_high: 125,
    amenities: ['2 Pools', 'Full Hookups', 'Showers', 'Laundry', 'Store', 'Dog Park', 'Basketball', 'Pickleball', 'Tennis', 'Playground', 'Propane Station', 'Pet Friendly'],
    site_types: ['RV', 'Tent', 'Cabin'],
    max_rig_length: 45,
    rating: 4.2,
    review_count: 1864,
    images: [
      'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800',
      'https://images.unsplash.com/photo-1476041800959-2f6bb412c8ce?w=800',
    ],
    booking_url: 'https://thousandtrails.com/california/tahoe-valley-campground',
    cancellation_policy: 'Contact campground directly. Thousand Trails membership may be required for some rates.',
    check_in: '4:00 PM',
    check_out: '11:00 AM',
    available: true,
    season: 'Year-round',
    phone: '(530) 541-2222',
    known_issues: 'WiFi unreliable; tight sites; helicopter noise from nearby hospital; no wood/charcoal fires May–Nov.',
  },
  {
    id: '2',
    name: 'Lake Tahoe KOA Journey',
    slug: 'lake-tahoe-koa',
    description: 'Family KOA campground 4 miles from Lake Tahoe\'s south shore. Heated pool, walking trails along Echo Creek, full hookup RV sites, and unique lodging including a 1940s chalet and vintage Airstream.',
    location: 'South Lake Tahoe, CA',
    lat: 38.8454,
    lng: -120.0293,
    price_per_night: 89,
    price_high: 180,
    amenities: ['Full/Partial Hookups', 'Heated Pool', 'Showers', 'Laundry', 'Store', 'WiFi', 'Pet Friendly', 'Fire Pits', 'Playground', 'Creek Trails'],
    site_types: ['RV', 'Tent', 'Cabin', 'Chalet', 'Airstream'],
    max_rig_length: 40,
    rating: 3.9,
    review_count: 518,
    images: [
      'https://images.unsplash.com/photo-1537225228614-56cc3556d7ed?w=800',
      'https://images.unsplash.com/photo-1510312305653-8ed496efae75?w=800',
    ],
    booking_url: 'https://koa.com/campgrounds/lake-tahoe/',
    cancellation_policy: 'Full refund if cancelled 7+ days before arrival. No refund within 7 days. KOA Rewards saves 10%.',
    check_in: '1:00 PM',
    check_out: '11:00 AM',
    available: true,
    season: 'Year-round',
    phone: '(530) 577-3693',
    known_issues: 'Heavy Highway 50 noise; high prices for amenities offered; 4 miles from lake; electricity outages reported.',
  },
  {
    id: '3',
    name: 'Zephyr Cove RV & Campground',
    slug: 'zephyr-cove',
    description: 'Federal campground on the southeast shore with beach access across Highway 50. RV sites with full hookups, walk-in tent sites, marina, restaurant, and paddlewheeler cruises.',
    location: 'Zephyr Cove, NV',
    lat: 38.9932,
    lng: -119.9358,
    price_per_night: 43,
    price_high: 100,
    amenities: ['Water+Sewer+Electric (RV)', 'Beach Access', 'Marina', 'Restaurant', 'Watercraft Rentals', 'Horseback Riding', 'Showers', 'Pet Friendly'],
    site_types: ['RV', 'Tent', 'Airstream Rental'],
    max_rig_length: 50,
    rating: 3.5,
    review_count: 512,
    images: [
      'https://images.unsplash.com/photo-1571863533956-01c88e79957e?w=800',
      'https://images.unsplash.com/photo-1559521783-1d1599583485?w=800',
    ],
    booking_url: 'https://www.recreation.gov/camping/campgrounds/10097082',
    cancellation_policy: 'Recreation.gov standard policy. $20 cancellation fee within 48 hours of arrival.',
    check_in: '11:00 AM',
    check_out: '11:00 AM',
    available: true,
    season: 'Year-round',
    phone: '(775) 589-4907',
    known_issues: 'Walk-in tent sites require hiking gear uphill; highway noise; sites cramped; $30/day damage deposit not disclosed upfront; WiFi only in lobby.',
  },
  {
    id: '4',
    name: 'Camp Richardson Resort',
    slug: 'camp-richardson',
    description: 'Historic resort campground directly on Lake Tahoe\'s south shore. Steps from the beach with paved bike paths along the lake, restaurant, ice cream parlor (summer), marina, and bike rentals.',
    location: 'South Lake Tahoe, CA',
    lat: 38.9384,
    lng: -120.0657,
    price_per_night: 55,
    price_high: 95,
    amenities: ['Beach Access (direct)', 'Restaurant', 'Ice Cream Parlor', 'Marina', 'Bike Rentals', 'Store', 'Fire Pits', 'Bear Boxes', 'Showers', 'Paved Bike Paths'],
    site_types: ['RV', 'Tent', 'Cabin'],
    max_rig_length: 35,
    rating: 4.4,
    review_count: 621,
    images: [
      'https://images.unsplash.com/photo-1533873984035-25970ab07461?w=800',
      'https://images.unsplash.com/photo-1487730116645-74489c95b41b?w=800',
    ],
    booking_url: 'https://camprichardson.com/camping/',
    cancellation_policy: 'Full refund 30+ days before. 50% refund 15–29 days. No refund within 14 days.',
    check_in: '2:00 PM',
    check_out: '12:00 PM',
    available: true,
    season: 'May - October',
    phone: 'See website',
    known_issues: 'Books up very fast; summer only season; limited RV hookup options.',
  },
  {
    id: '5',
    name: 'Nevada Beach Campground',
    slug: 'nevada-beach',
    description: 'Most sought-after campground at Lake Tahoe. Pine forest directly on the Nevada shoreline. Books out in seconds when reservations open exactly 6 months in advance.',
    location: 'Zephyr Cove, NV',
    lat: 38.9712,
    lng: -119.9441,
    price_per_night: 29,
    price_high: 54,
    amenities: ['Beach Access (direct)', 'Fire Pits', 'Flush Toilets', 'Picnic Tables', 'Bear Boxes', 'Pet Friendly'],
    site_types: ['RV', 'Tent'],
    max_rig_length: 45,
    rating: 4.6,
    review_count: 489,
    images: [
      'https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?w=800',
      'https://images.unsplash.com/photo-1500581276021-a4469e3a2699?w=800',
    ],
    booking_url: 'https://www.recreation.gov/camping/campgrounds/232454',
    cancellation_policy: 'Full refund minus $10 service fee if cancelled 4+ days before. No refund within 3 days.',
    check_in: '2:00 PM',
    check_out: '12:00 PM',
    available: false,
    season: 'May - October',
    phone: 'Recreation.gov',
    known_issues: 'No showers; no hookups; no dump station. Books in SECONDS — set a reminder for exactly 6 months before your target date at 7am PST.',
  },
  {
    id: '6',
    name: 'Fallen Leaf Campground',
    slug: 'fallen-leaf',
    description: 'National Forest campground 6 miles from South Lake Tahoe near Fallen Leaf Lake. Largest federal campground in the area with 206 sites including yurts. Senior pass = 50% off.',
    location: 'South Lake Tahoe, CA',
    lat: 38.8993,
    lng: -120.0549,
    price_per_night: 35,
    price_high: 55,
    amenities: ['Flush Toilets', 'Coin Showers', 'Dump Station', 'Fire Pits', 'Bear Boxes', 'Water Spigots', 'Walk to Fallen Leaf Lake', 'Pet Friendly'],
    site_types: ['RV', 'Tent', 'Yurt'],
    max_rig_length: 40,
    rating: 4.5,
    review_count: 284,
    images: [
      'https://images.unsplash.com/photo-1445308394109-4ec2920981b1?w=800',
      'https://images.unsplash.com/photo-1496080174650-637e3f22fa03?w=800',
    ],
    booking_url: 'https://www.recreation.gov/camping/campgrounds/232450',
    cancellation_policy: 'Full refund minus $10 service fee if cancelled 4+ days before. No refund within 3 days.',
    check_in: '2:00 PM',
    check_out: '12:00 PM',
    available: true,
    season: 'Mid-May - Mid-October',
    phone: 'Recreation.gov',
    known_issues: 'RV generator noise common; coin showers only. 206 sites means better availability than Nevada Beach. Book 6 months out.',
  },
]

export type Campground = typeof campgrounds[0]
