export const campgrounds = [
  {
    id: '1',
    name: 'Tahoe Valley Campground',
    slug: 'tahoe-valley',
    tagline: 'Best amenities, year-round access, heart of South Lake Tahoe',
    description: 'The most amenity-rich campground at Lake Tahoe and one of the only year-round options on either shore. Run by Encore/Thousand Trails, Tahoe Valley sits in the heart of South Lake Tahoe within walking distance of groceries, restaurants, and the Pope Baldwin Bike Path. Two pools, a massive dog park, pickleball, basketball, volleyball, movie nights, and food trucks make this the top pick for families. Not rustic — but reliable, hookup-equipped, and always open.',
    location: 'South Lake Tahoe, CA',
    address: '1175 Melba Dr, South Lake Tahoe, CA 96150',
    lat: 38.9183,
    lng: -120.0324,
    price_per_night: 75,
    price_high: 125,
    amenities: ['2 Pools', 'Full Hookups (30/50A)', 'Hot Showers', 'Laundry', 'General Store', 'Dog Park', 'Basketball', 'Pickleball', 'Tennis', 'Horseshoes', 'Volleyball', 'Playground', 'Movie Nights', 'Food Trucks', 'Propane Station', 'Air Station', 'Cable TV', 'Pet Friendly'],
    site_types: ['RV', 'Tent', 'Cabin'],
    max_rig_length: 45,
    rating: 4.2,
    review_count: 1864,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=1200&q=80',
        alt: 'Tahoe Valley Campground RV sites surrounded by tall Sierra Nevada pine trees at sunset',
        title: 'Tahoe Valley RV Sites — South Lake Tahoe',
        caption: 'Full hookup RV sites under towering pines'
      },
      {
        url: 'https://images.unsplash.com/photo-1537225228614-56cc3556d7ed?w=1200&q=80',
        alt: 'Camping cabin nestled among pine trees at Lake Tahoe campground',
        title: 'Tahoe Valley Cabin Rentals',
        caption: 'Cozy cabins with kitchen — perfect for families'
      },
      {
        url: 'https://images.unsplash.com/photo-1445308394109-4ec2920981b1?w=1200&q=80',
        alt: 'Campfire burning in stone fire ring at dusk surrounded by pine forest',
        title: 'Evening campfire at Tahoe Valley',
        caption: 'Propane fires allowed year-round (no wood May–Nov)'
      },
    ],
    booking_url: 'https://thousandtrails.com/california/tahoe-valley-campground',
    cancellation_policy: 'Contact campground directly at (530) 541-2222. Thousand Trails membership may be required for some rates. Seasonal and annual site rates available.',
    check_in: '4:00 PM',
    check_out: '11:00 AM',
    available: true,
    season: 'Year-round',
    phone: '(530) 541-2222',
    elevation: '6,265 ft',
    total_sites: 413,
    hookups: 'Full (water, electric 30/50A, sewer)',
    nearest_beach: '3 miles to Lake Tahoe beaches',
    nearest_grocery: 'Walking distance — Raley\'s 0.3 miles',
    pro_tips: [
      '🚗 Pull-through sites available — ask for one when booking if you have a large rig',
      '📶 Don\'t rely on their WiFi — it\'s widely reported as broken. Use a cellular booster or hotspot',
      '🐻 Bears are active — always store food in your vehicle or bear box, even during the day',
      '🎬 Saturday morning breakfast for a small fee is a hidden gem — worth waking up for',
      '🚲 You\'re minutes from the Pope Baldwin Bike Path — bring bikes, it\'s flat and gorgeous',
      '🌙 No nighttime enforcement of quiet hours — light sleepers should bring earplugs',
    ],
    known_issues: 'WiFi consistently broken; tight site spacing; helicopter noise from adjacent hospital; no wood/charcoal fires May–Nov; no nighttime staff for quiet hour enforcement.',
    best_for: ['Families', 'Full-hookup RVers', 'Year-round campers', 'First-timers'],
    nearby: ['Pope Baldwin Bike Path (0.5 mi)', 'Fallen Leaf Lake (3 mi)', 'Heavenly Ski Resort (4 mi)', 'South Lake Tahoe casinos (5 mi)'],
  },
  {
    id: '2',
    name: 'Lake Tahoe KOA Journey',
    slug: 'lake-tahoe-koa',
    tagline: 'Family-friendly with heated pool, creek trails, and unique lodging',
    description: 'A well-run KOA campground tucked beneath tall Sierra pines alongside Echo Creek, 4 miles from Lake Tahoe\'s south shore. Known for genuinely friendly staff, spotless facilities, and a heated pool. Lodging options are exceptional — including a 1940s Alpine chalet that sleeps 6 and a vintage Airstream. RV sites are shaded asphalt pads. Highway 50 noise is real, but quiet hours are well enforced. Best KOA in the Tahoe region for overall execution.',
    location: 'South Lake Tahoe, CA',
    address: '760 N Hwy 50, South Lake Tahoe, CA 96150',
    lat: 38.8454,
    lng: -120.0293,
    price_per_night: 89,
    price_high: 180,
    amenities: ['Full/Partial Hookups', 'Heated Pool', 'Hot Showers', 'Laundry', 'Camp Store', 'WiFi', 'Pet Friendly', 'Fire Pits', 'Playground', 'Creek Walking Trails', 'KOA Rewards Program'],
    site_types: ['RV', 'Tent', 'Deluxe Cabin', '1940s Chalet', 'Vintage Airstream'],
    max_rig_length: 40,
    rating: 3.9,
    review_count: 518,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1510312305653-8ed496efae75?w=1200&q=80',
        alt: 'Tent camping site with campfire in Sierra Nevada pine forest near Lake Tahoe',
        title: 'Lake Tahoe KOA Tent Sites — South Lake Tahoe',
        caption: 'Shaded tent sites alongside Echo Creek'
      },
      {
        url: 'https://images.unsplash.com/photo-1571863533956-01c88e79957e?w=1200&q=80',
        alt: 'Vintage Airstream trailer parked in pine forest at glamping campground',
        title: 'Vintage Airstream Lodging at Lake Tahoe KOA',
        caption: 'Unique vintage Airstream accommodation — books fast'
      },
      {
        url: 'https://images.unsplash.com/photo-1533873984035-25970ab07461?w=1200&q=80',
        alt: 'Mountain forest campground with paved RV sites and tall pine trees in California',
        title: 'KOA RV Sites with Full Hookups',
        caption: 'Level asphalt RV pads with 30/50A hookups'
      },
    ],
    booking_url: 'https://koa.com/campgrounds/lake-tahoe/',
    cancellation_policy: 'Full refund if cancelled 7+ days before arrival. No refund within 7 days. KOA Rewards members save 10% — sign up free before booking.',
    check_in: '1:00 PM',
    check_out: '11:00 AM',
    available: true,
    season: 'Year-round',
    phone: '(530) 577-3693',
    reservations: '(800) 562-3477',
    elevation: '6,260 ft',
    total_sites: 'Mixed RV, tent, and lodging',
    hookups: 'Full (water, electric 30/50A, sewer) and partial',
    nearest_beach: '4 miles to South Lake Tahoe shore',
    nearest_grocery: '0.5 miles — several options on US-50',
    pro_tips: [
      '🏡 Book the 1940s Chalet for groups — loft sleeps 4, main floor sleeps 2, full kitchen. One of the most unique stays at Tahoe',
      '💳 Sign up for KOA Rewards (free) before booking — saves 10% every stay',
      '🌊 Echo Creek sites are the best — request one near the creek when booking',
      '🚗 US-50 sites are noisy — ask specifically for sites furthest from the highway',
      '🎿 This KOA stays open in winter — closest full-hookup campground to Heavenly Ski Resort',
      '⚡ Electricity outages have been reported — bring a surge protector for electronics',
    ],
    known_issues: 'Heavy Highway 50 noise on road-facing sites; prices on the high side for what you get; 4 miles from the lake; some electricity inconsistencies reported.',
    best_for: ['Families', 'Groups', 'Winter skiing trips', 'KOA Rewards members'],
    nearby: ['Echo Lake (3 mi)', 'Heavenly Mountain Resort (4 mi)', 'South Lake Tahoe (4 mi)', 'Emerald Bay (8 mi)'],
  },
  {
    id: '3',
    name: 'Zephyr Cove RV & Campground',
    slug: 'zephyr-cove',
    tagline: 'Beach access, marina, paddlewheeler cruises — full resort experience',
    description: 'A full-service resort campground on Lake Tahoe\'s scenic southeast shore managed by the USFS and booked via Recreation.gov. The resort itself is a destination: mile-long sandy beach across the highway, the iconic M.S. Dixie II paddlewheeler, marina with boat and watercraft rentals, horseback riding, and a full restaurant. RV sites have full hookups and can accommodate rigs up to 50ft. Walk-in tent sites are uphill from parking — pack light. The most activity-dense campground at Tahoe.',
    location: 'Zephyr Cove, NV',
    address: '760 US-50, Zephyr Cove, NV 89448',
    lat: 38.9932,
    lng: -119.9358,
    price_per_night: 43,
    price_high: 100,
    amenities: ['Full Hookups RV (water, sewer, electric)', 'Beach Access (across hwy)', 'Marina', 'Restaurant & Bar', 'Watercraft Rentals', 'Paddlewheeler Cruises (MS Dixie II)', 'Horseback Riding', 'Private Hot Showers', 'Flush Toilets', 'General Store', 'Pet Friendly', 'ATV/Snowmobile Tours'],
    site_types: ['RV (up to 50ft)', 'Tent (drive-in)', 'Tent (walk-in)', 'Airstream Rental'],
    max_rig_length: 50,
    rating: 3.5,
    review_count: 512,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1559521783-1d1599583485?w=1200&q=80',
        alt: 'Lake Tahoe crystal clear blue water and sandy Nevada beach at sunset',
        title: 'Zephyr Cove Beach — Lake Tahoe\'s Southeast Shore',
        caption: 'Beach is steps across Highway 50 from the campground'
      },
      {
        url: 'https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?w=1200&q=80',
        alt: 'RV parked at pine forest campsite on the shores of Lake Tahoe Nevada',
        title: 'Zephyr Cove Full Hookup RV Sites',
        caption: 'Full hookup sites accommodate rigs up to 50ft'
      },
      {
        url: 'https://images.unsplash.com/photo-1487730116645-74489c95b41b?w=1200&q=80',
        alt: 'Campfire at lakeside campsite with view of Lake Tahoe in background',
        title: 'Zephyr Cove Lakeside Camping',
        caption: 'Some sites offer glimpses of the lake through the pines'
      },
    ],
    booking_url: 'https://www.recreation.gov/camping/campgrounds/10097082',
    cancellation_policy: 'Recreation.gov standard: full refund minus $10 service fee if cancelled 4+ days before. $20 cancellation fee within 48 hours of arrival.',
    check_in: '11:00 AM',
    check_out: '11:00 AM',
    available: true,
    season: 'Year-round',
    phone: '(775) 589-4907',
    elevation: '6,225 ft',
    total_sites: '93 RV + 47 walk-in + 10 drive-in = 150 total',
    hookups: 'Full hookup RV (water, sewer, electric included in rate)',
    nearest_beach: 'Across Highway 50 — 2 minute walk',
    nearest_grocery: 'Safeway at Round Hill Center, 2 miles',
    pro_tips: [
      '⚠️ Walk-in tent sites mean hiking your gear uphill from the parking lot — bring a cart or pack light',
      '💰 A $30/day damage deposit is charged at check-in — NOT disclosed on Recreation.gov. Bring your credit card',
      '🛥️ Book the M.S. Dixie II sunset cruise in advance — it fills up fast in summer and it\'s unforgettable',
      '🔇 WiFi is only available in the resort lobby — not at your campsite. Download maps and entertainment before you arrive',
      '🚐 Sites #1–20 closest to the beach but also closest to Highway 50 noise. Sites #60–93 are quieter and more wooded',
      '🐴 Horseback riding reservations fill up — book through Zephyr Cove Stables the same day you book camping',
    ],
    known_issues: 'Highway noise significant on some sites; very tight spacing between sites; $30/day damage deposit not disclosed at booking; check-in is at the lodge across the highway; walk-in tent sites are a legitimate hike.',
    best_for: ['Families wanting resort activities', 'RVers up to 50ft', 'Lake activity seekers', 'Couples'],
    nearby: ['Zephyr Cove Beach (across hwy)', 'Stateline Casinos (3 mi)', 'Sand Harbor (8 mi)', 'South Lake Tahoe (5 mi)'],
  },
  {
    id: '4',
    name: 'Camp Richardson Resort',
    slug: 'camp-richardson',
    tagline: 'Historic lakefront resort with direct beach access and bike paths',
    description: 'The crown jewel of South Lake Tahoe camping. Camp Richardson sits directly on the southwest shore with paved bike paths that run along the lake to multiple beaches. The historic resort includes a full restaurant (The Grove), an ice cream parlor (summer only), a marina with parasailing and boat rentals, and bike rental shop. Campfire rings at every site. RV hookups are more limited than other parks and haphazardly placed — bring long water and electric extensions. Best pure lakefront camping experience at Tahoe.',
    location: 'South Lake Tahoe, CA',
    address: '1900 Jameson Beach Rd, South Lake Tahoe, CA 96150',
    lat: 38.9384,
    lng: -120.0657,
    price_per_night: 55,
    price_high: 95,
    amenities: ['Direct Beach Access', 'Restaurant (The Grove)', 'Ice Cream Parlor (summer)', 'Marina', 'Parasailing & Boat Rentals', 'Bike Rentals', 'General Store', 'Fire Pits', 'Bear Boxes', 'Hot Showers', 'Paved Lakeside Bike Path', 'Emerald Bay Cruise Access'],
    site_types: ['RV', 'Tent', 'Cabin', 'Beach Cabin'],
    max_rig_length: 35,
    rating: 4.4,
    review_count: 621,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1500581276021-a4469e3a2699?w=1200&q=80',
        alt: 'Pine forest campsite steps from Lake Tahoe\'s crystal blue water at Camp Richardson',
        title: 'Camp Richardson — Directly on Lake Tahoe\'s Shore',
        caption: 'Walk from your site to the beach in minutes'
      },
      {
        url: 'https://images.unsplash.com/photo-1476041800959-2f6bb412c8ce?w=1200&q=80',
        alt: 'Bicycle path through pine forest along Lake Tahoe shoreline on a sunny day',
        title: 'Paved Lakeside Bike Path at Camp Richardson',
        caption: 'Flat bike paths connect multiple beaches along the south shore'
      },
      {
        url: 'https://images.unsplash.com/photo-1496080174650-637e3f22fa03?w=1200&q=80',
        alt: 'Tent camping in tall pine forest at a Lake Tahoe national forest campground',
        title: 'Camp Richardson Tent Sites in Pine Forest',
        caption: 'Spacious tent sites surrounded by towering Sierra pines'
      },
    ],
    booking_url: 'https://camprichardson.com/camping/',
    cancellation_policy: 'Full refund 30+ days before arrival. 50% refund 15–29 days. No refund within 14 days. Strictly enforced.',
    check_in: '2:00 PM',
    check_out: '12:00 PM',
    available: true,
    season: 'May - October',
    phone: 'See camprichardson.com',
    elevation: '6,225 ft',
    total_sites: 'Over 200 (tent, RV, cabin)',
    hookups: 'Limited water and electric; full hookups rare — bring 50ft+ extension cords and hoses',
    nearest_beach: 'Steps away — directly on the lake',
    nearest_grocery: 'South Lake Tahoe town center, 3 miles',
    pro_tips: [
      '🚲 Rent bikes at the resort and ride the Pope Baldwin Bike Path south — flat, paved, and absolutely stunning along the lake',
      '🍦 The ice cream parlor is summer only and worth a trip even if you\'re not camping. Lines get long — go before noon',
      '🛶 Book marina activities early — parasailing, kayak rentals, and the Emerald Bay boat tour fill up weeks ahead in July/August',
      '🔌 RV hookups are limited and not in standard positions. Bring a 50ft water hose and 30ft electric extension — you\'ll need them',
      '🐕 No dogs allowed at Camp Richardson — plan accordingly',
      '📅 Last-minute openings happen when people cancel. Check daily if you\'re hoping to snag a spot in peak season',
    ],
    known_issues: 'No dogs allowed. RV hookups limited and awkwardly positioned. Books up very fast — sometimes months in advance. Summer-only season.',
    best_for: ['Beach lovers', 'Cyclists', 'Families (no dogs)', 'Water sports enthusiasts'],
    nearby: ['Fallen Leaf Lake (2 mi)', 'Emerald Bay (5 mi)', 'Pope Beach (0.5 mi)', 'South Lake Tahoe (3 mi)'],
  },
  {
    id: '5',
    name: 'Nevada Beach Campground',
    slug: 'nevada-beach',
    tagline: 'The most scenic campground at Tahoe — books in seconds, worth every effort',
    description: 'Widely regarded as the best campground at Lake Tahoe. Fifty-six spacious, paved sites nestled in Jeffrey pines at 6,100 feet on the Nevada shore, most with lake views. Nearly a mile of the widest, most pristine beach on the lake is a short walk away. Sites are larger and more spread out than anywhere else at Tahoe — actual privacy. No hookups, no showers, but the location and setting are unmatched. Opens May 22, 2026. Reservations release exactly 6 months in advance on Recreation.gov at 7am PST — and sell out in minutes.',
    location: 'Zephyr Cove, NV',
    address: 'Elks Point Rd, Zephyr Cove, NV 89448',
    lat: 38.9712,
    lng: -119.9441,
    price_per_night: 47,
    price_high: 49,
    amenities: ['Direct Beach Access (0.3 mi walk)', 'Flush Toilets', 'Potable Water', 'Fire Rings & Grills', 'Bear Boxes (every site)', 'Picnic Tables', 'Paved Parking Aprons', 'Trash & Recycling', 'Pet Friendly (in campground)', 'Paddleboard & Kayak Rentals (summer)', 'Lam Wa Tah Trail access'],
    site_types: ['RV (no hookups)', 'Tent'],
    max_rig_length: 45,
    rating: 4.6,
    review_count: 489,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=1200&q=80',
        alt: 'Nevada Beach campsite with Jeffrey pine trees and glimpse of Lake Tahoe in background',
        title: 'Nevada Beach Campground — Best Sites at Lake Tahoe',
        caption: 'Spacious paved sites with lake views through the pines'
      },
      {
        url: 'https://images.unsplash.com/photo-1559521783-1d1599583485?w=1200&q=80',
        alt: 'Wide sandy Nevada Beach on Lake Tahoe with crystal clear blue water and mountain backdrop',
        title: 'Nevada Beach — Nearly a Mile of White Sand',
        caption: 'The widest beach on Lake Tahoe, steps from your campsite'
      },
      {
        url: 'https://images.unsplash.com/photo-1445308394109-4ec2920981b1?w=1200&q=80',
        alt: 'Morning mist over Lake Tahoe seen from pine forest campsite at Nevada Beach',
        title: 'Morning at Nevada Beach Campground',
        caption: 'Sites #14 and #28 are perennial favorites for lake views'
      },
    ],
    booking_url: 'https://www.recreation.gov/camping/campgrounds/232454',
    cancellation_policy: 'Full refund minus $10 service fee if cancelled 4+ days before arrival. No refund within 3 days. Cancellations DO become available to others — check Recreation.gov daily if you missed the opening window.',
    check_in: '12:00 PM',
    check_out: '12:00 PM',
    available: false,
    season: 'May 22 - September 2026',
    phone: '(775) 588-5562',
    elevation: '6,100 ft',
    total_sites: '56 sites',
    hookups: 'None — dry camping only. Nearest dump stations: Zephyr Cove (2 mi), Camp Richardson (4 mi)',
    nearest_beach: '0.3 mile walk — Nevada Beach (0.7 miles long, one of the widest on the lake)',
    nearest_grocery: 'Safeway at Round Hill Center, 2 miles',
    pro_tips: [
      '⏰ Set an alarm for 7:00 AM PST exactly 6 months before your target date — reservations open then and sell out in under 2 minutes',
      '🎯 Request sites #14 or #28 — both praised repeatedly in reviews for views and spacing. Site #39 is right across from restrooms',
      '☀️ Sites #24 and #26 are less wooded — better for solar panels on your RV',
      '🔄 Check Recreation.gov daily for cancellations — people cancel all the time, especially for weekdays',
      '🐕 Dogs allowed in the campground and on the south end of Nevada Beach — one of Tahoe\'s only dog-friendly lake beaches',
      '🚿 No showers on site. The nearest are at Zephyr Cove Resort (2 mi) — pay per use',
      '🌊 Lam Wa Tah Trail starts here — 2.6 mile flat trail through the woods along the lake, perfect for morning walks',
    ],
    known_issues: 'No hookups, no showers, no dump station on site. Extremely difficult to get reservations. Maximum 14-night stay per calendar year. Pets not allowed on the beach itself (campground only).',
    best_for: ['Beach campers', 'Tent campers', 'Dog owners (south beach)', 'Anyone seeking the best views at Tahoe'],
    nearby: ['Nevada Beach (0.3 mi)', 'Stateline Casinos (3 mi)', 'Zephyr Cove Resort (2 mi)', 'South Lake Tahoe (4 mi)'],
  },
  {
    id: '6',
    name: 'Fallen Leaf Campground',
    slug: 'fallen-leaf',
    description: 'The best-kept secret at South Lake Tahoe. Fallen Leaf sits 6 miles from town in a stunning National Forest setting on the shores of Fallen Leaf Lake — a pristine alpine lake that\'s calmer and less crowded than Tahoe itself. With 206 sites including yurts (Town Yurts), this is the largest federal campground in the area and offers better availability than Nevada Beach. Large, spacious sites. Bike ride to Fallen Leaf Lake beach is magical. America the Beautiful Senior/Access Pass gets 50% off the nightly rate.',
    tagline: 'Hidden gem: alpine lake, spacious sites, better availability than Nevada Beach',
    location: 'South Lake Tahoe, CA',
    address: '2165 Fallen Leaf Rd, South Lake Tahoe, CA 96150',
    lat: 38.8993,
    lng: -120.0549,
    price_per_night: 35,
    price_high: 55,
    amenities: ['Walk to Fallen Leaf Lake Beach', 'Flush Toilets', 'Coin-Op Hot Showers ($0.25)', 'Dump Station', 'Fire Pits with Grates', 'Bear Boxes (every site)', 'Potable Water', 'Picnic Tables', 'Pet Friendly', 'Bike Path to Lake', 'Glen Alpine Trailhead Access'],
    site_types: ['RV (no hookups)', 'Tent', 'Yurt (Town Yurt)'],
    max_rig_length: 40,
    rating: 4.5,
    review_count: 284,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1533873984035-25970ab07461?w=1200&q=80',
        alt: 'Fallen Leaf Lake surrounded by Sierra Nevada pine forest and granite mountains at sunrise',
        title: 'Fallen Leaf Lake — Tahoe\'s Hidden Alpine Gem',
        caption: 'Fallen Leaf Lake is calmer, less crowded, and equally stunning'
      },
      {
        url: 'https://images.unsplash.com/photo-1496080174650-637e3f22fa03?w=1200&q=80',
        alt: 'Spacious campsite in tall pine forest at Fallen Leaf National Forest campground',
        title: 'Fallen Leaf Campground — Large Spacious Sites',
        caption: 'Sites are noticeably larger than other Tahoe campgrounds'
      },
      {
        url: 'https://images.unsplash.com/photo-1476041800959-2f6bb412c8ce?w=1200&q=80',
        alt: 'Misty morning light filtering through aspen and pine trees at Lake Tahoe forest campground',
        title: 'Morning Light at Fallen Leaf Campground',
        caption: 'Aspens turn brilliant yellow in fall — September is magical here'
      },
    ],
    booking_url: 'https://www.recreation.gov/camping/campgrounds/232450',
    cancellation_policy: 'Full refund minus $10 service fee if cancelled 4+ days before arrival. No refund within 3 days.',
    check_in: '2:00 PM',
    check_out: '12:00 PM',
    available: true,
    season: 'Mid-May - Mid-October',
    phone: 'Recreation.gov — (877) 444-6777',
    elevation: '6,377 ft',
    total_sites: '206 sites + yurts',
    hookups: 'None — dry camping. Dump station on site.',
    nearest_beach: '0.25 mile to Fallen Leaf Lake beach (walk or bike)',
    nearest_grocery: 'South Lake Tahoe, 6 miles',
    pro_tips: [
      '🍂 Visit in September for fall foliage — aspens turn gold and the campground is far less crowded',
      '🎿 Coin showers are $0.25 per minute — bring a handful of quarters and time your shower',
      '🌿 The campground road crosses the entrance to Fallen Leaf Lake — bike or walk to the beach in under 5 minutes',
      '⚡ No hookups means generators are allowed — RV generator noise can be an issue on busy weekends. Bring earplugs',
      '🥾 Glen Alpine Trailhead is accessible from the campground — gateway to Desolation Wilderness day hikes',
      '🎫 America the Beautiful Senior Pass (America the Beautiful $80/year) cuts your rate in half — $17–$27/night instead of $35–$55',
      '📅 206 sites means better odds than Nevada Beach — but still book 6 months ahead for summer weekends',
    ],
    known_issues: 'No hookups. Coin showers only. Generator noise common from RVs. 6 miles from South Lake Tahoe town. No cell signal in parts of the campground.',
    best_for: ['Budget campers', 'Hikers', 'Cyclists', 'Fall foliage seekers', 'Senior pass holders'],
    nearby: ['Fallen Leaf Lake (0.25 mi)', 'Glen Alpine Trailhead (0.5 mi)', 'Emerald Bay (4 mi)', 'Desolation Wilderness (1 mi)'],
  },
]

export type Campground = typeof campgrounds[0]
