export const campgrounds = [
  {
    id: '1',
    name: 'Tahoe Valley Campground',
    slug: 'tahoe-valley',
    description: 'Large RV resort in a forested setting near South Lake Tahoe. Pull-through sites, full hookups, and easy access to town.',
    location: 'South Lake Tahoe, CA',
    lat: 38.9183,
    lng: -120.0324,
    price_per_night: 75,
    amenities: ['Full Hookups', 'Showers', 'WiFi', 'Pool', 'Pet Friendly', 'Pull-Through Sites'],
    site_types: ['RV', 'Tent', 'Cabin'],
    max_rig_length: 45,
    rating: 4.2,
    review_count: 342,
    images: [
      'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800',
      'https://images.unsplash.com/photo-1476041800959-2f6bb412c8ce?w=800',
    ],
    booking_url: 'https://www.camperwatch.com/reservations',
    cancellation_policy: 'Full refund if cancelled 14+ days before arrival. 50% refund 7-13 days. No refund within 7 days.',
    check_in: '2:00 PM',
    check_out: '11:00 AM',
    available: true,
    season: 'Year-round',
  },
  {
    id: '2',
    name: 'Lake Tahoe KOA Journey',
    slug: 'lake-tahoe-koa',
    description: 'Family-friendly KOA campground one mile from Lake Tahoe. Cabins, RV sites, and tent sites available.',
    location: 'South Lake Tahoe, CA',
    lat: 38.8454,
    lng: -120.0293,
    price_per_night: 89,
    amenities: ['Electric Hookups', 'Showers', 'WiFi', 'Store', 'Pet Friendly', 'Fire Pits'],
    site_types: ['RV', 'Tent', 'Cabin', 'Glamping'],
    max_rig_length: 40,
    rating: 3.9,
    review_count: 518,
    images: [
      'https://images.unsplash.com/photo-1537225228614-56cc3556d7ed?w=800',
      'https://images.unsplash.com/photo-1510312305653-8ed496efae75?w=800',
    ],
    booking_url: 'https://koa.com/campgrounds/lake-tahoe/',
    cancellation_policy: 'Full refund if cancelled 7+ days before arrival. No refund within 7 days.',
    check_in: '1:00 PM',
    check_out: '11:00 AM',
    available: true,
    season: 'April - October',
  },
  {
    id: '3',
    name: 'Zephyr Cove Resort',
    slug: 'zephyr-cove',
    description: 'Award-winning RV park and campground on the southeast shore of Lake Tahoe. Walking distance to beach and marina.',
    location: 'Zephyr Cove, NV',
    lat: 38.9932,
    lng: -119.9358,
    price_per_night: 95,
    amenities: ['Water & Electric', 'Beach Access', 'Marina', 'Restaurant', 'Pet Friendly', 'Airstream Rentals'],
    site_types: ['RV', 'Tent', 'Airstream'],
    max_rig_length: 35,
    rating: 3.5,
    review_count: 375,
    images: [
      'https://images.unsplash.com/photo-1571863533956-01c88e79957e?w=800',
      'https://images.unsplash.com/photo-1559521783-1d1599583485?w=800',
    ],
    booking_url: 'https://www.zephyrcove.com/lodging/zephyr-cove-rv-campground/',
    cancellation_policy: 'Full refund if cancelled 48+ hours before arrival. $20 fee for cancellations within 48 hours.',
    check_in: '3:00 PM',
    check_out: '11:00 AM',
    available: true,
    season: 'Year-round',
  },
  {
    id: '4',
    name: 'Camp Richardson Resort',
    slug: 'camp-richardson',
    description: 'Historic resort on the southwest shore of Lake Tahoe with tent sites, RV sites, and cabins. Steps from the beach.',
    location: 'South Lake Tahoe, CA',
    lat: 38.9384,
    lng: -120.0657,
    price_per_night: 65,
    amenities: ['Beach Access', 'Store', 'Restaurant', 'Bike Rentals', 'Fire Pits', 'Showers'],
    site_types: ['RV', 'Tent', 'Cabin'],
    max_rig_length: 35,
    rating: 4.4,
    review_count: 621,
    images: [
      'https://images.unsplash.com/photo-1533873984035-25970ab07461?w=800',
      'https://images.unsplash.com/photo-1487730116645-74489c95b41b?w=800',
    ],
    booking_url: 'https://camprichardson.com/camping/',
    cancellation_policy: 'Full refund if cancelled 30+ days before arrival. 50% refund 15-29 days. No refund within 14 days.',
    check_in: '2:00 PM',
    check_out: '12:00 PM',
    available: true,
    season: 'May - October',
  },
  {
    id: '5',
    name: 'Nevada Beach Campground',
    slug: 'nevada-beach',
    description: 'One of the most sought-after campgrounds at Lake Tahoe. Pine forest setting directly on the Nevada beach shoreline.',
    location: 'Zephyr Cove, NV',
    lat: 38.9712,
    lng: -119.9441,
    price_per_night: 38,
    amenities: ['Beach Access', 'Fire Pits', 'Flush Toilets', 'Pet Friendly'],
    site_types: ['RV', 'Tent'],
    max_rig_length: 45,
    rating: 4.6,
    review_count: 489,
    images: [
      'https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?w=800',
      'https://images.unsplash.com/photo-1500581276021-a4469e3a2699?w=800',
    ],
    booking_url: 'https://www.recreation.gov/camping/campgrounds/232454',
    cancellation_policy: 'Full refund minus $10 service fee if cancelled 4+ days before arrival. No refund within 3 days.',
    check_in: '2:00 PM',
    check_out: '12:00 PM',
    available: false,
    season: 'May - October',
  },
  {
    id: '6',
    name: 'Fallen Leaf Campground',
    slug: 'fallen-leaf',
    description: 'National Forest campground near Fallen Leaf Lake, 6 miles from South Lake Tahoe. Large spacious sites.',
    location: 'South Lake Tahoe, CA',
    lat: 38.8993,
    lng: -120.0549,
    price_per_night: 42,
    amenities: ['Flush Toilets', 'Showers', 'Fire Pits', 'Bear Boxes', 'Dump Station'],
    site_types: ['RV', 'Tent', 'Yurt'],
    max_rig_length: 40,
    rating: 4.5,
    review_count: 284,
    images: [
      'https://images.unsplash.com/photo-1445308394109-4ec2920981b1?w=800',
      'https://images.unsplash.com/photo-1496080174650-637e3f22fa03?w=800',
    ],
    booking_url: 'https://www.recreation.gov/camping/campgrounds/232450',
    cancellation_policy: 'Full refund minus $10 service fee if cancelled 4+ days before arrival. No refund within 3 days.',
    check_in: '2:00 PM',
    check_out: '12:00 PM',
    available: true,
    season: 'Mid-May - Mid-October',
  },
]

export type Campground = typeof campgrounds[0]
